# docker-compose.override.yml
services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 9090 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt
    ports:
      - "9091:9090" # Maps host port 9091 to container port 8000
